import numpy as np
import skfuzzy as fuzz
import skfuzzy.control as ctrl
import matplotlib.pyplot as plt

luas_lahan = ctrl.Antecedent(np.arange(0, 6.1, 0.1), 'luas_lahan')
produksi_padi = ctrl.Antecedent(np.arange(2, 8.1, 0.1), 'produksi_padi')
irigasi = ctrl.Antecedent(np.arange(0, 9.1, 0.1), 'irigasi')
subsidi = ctrl.Consequent(np.arange(1, 7.1, 0.1), 'subsidi')

luas_lahan['Sangat Kecil'] = fuzz.trimf(luas_lahan.universe, [0, 1, 2])
luas_lahan['Kecil'] = fuzz.trimf(luas_lahan.universe, [1, 2, 3])
luas_lahan['Sedang'] = fuzz.trimf(luas_lahan.universe, [2, 3, 4])
luas_lahan['Besar'] = fuzz.trimf(luas_lahan.universe, [3, 4, 5])
luas_lahan['Sangat Besar'] = fuzz.trimf(luas_lahan.universe, [4, 5, 6])

produksi_padi['Sangat Rendah'] = fuzz.trimf(produksi_padi.universe, [2, 3, 4])
produksi_padi['Rendah'] = fuzz.trimf(produksi_padi.universe, [3, 4, 5])
produksi_padi['Sedang'] = fuzz.trimf(produksi_padi.universe, [4, 5, 6])
produksi_padi['Tinggi'] = fuzz.trimf(produksi_padi.universe, [5, 6, 7]) 
produksi_padi['Sangat Tinggi'] = fuzz.trimf(produksi_padi.universe, [6, 7, 8])

irigasi['Sangat Buruk'] = fuzz.trimf(irigasi.universe, [0, 1.5, 3])
irigasi['Buruk'] = fuzz.trimf(irigasi.universe, [1.5, 3, 4.5])
irigasi['Sedang'] = fuzz.trimf(irigasi.universe, [3, 4.5, 6])
irigasi['Baik'] = fuzz.trimf(irigasi.universe, [4.5, 6, 7.5])
irigasi['Sangat Baik'] = fuzz.trimf(irigasi.universe, [6, 7.5, 9])

subsidi['Sangat Rendah'] = fuzz.trimf(subsidi.universe, [1, 2, 3])
subsidi['Rendah'] = fuzz.trimf(subsidi.universe, [2, 3, 4])
subsidi['Sedang'] = fuzz.trimf(subsidi.universe, [3, 4, 5])
subsidi['Tinggi'] = fuzz.trimf(subsidi.universe, [4, 5, 6])
subsidi['Sangat Tinggi'] = fuzz.trimf(subsidi.universe, [5, 6, 7])



rule1 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sangat Rendah'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule2 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Rendah'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule3 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sedang'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule4 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Tinggi'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule5 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sangat Tinggi'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule6 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sangat Rendah'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule7 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Rendah'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule8 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sedang'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule9 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Tinggi'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule10 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sangat Tinggi'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule11 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sangat Rendah'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule12 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Rendah'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule13 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sedang'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule14 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Tinggi'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule15 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sangat Tinggi'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule16 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sangat Rendah'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule17 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Rendah'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule18 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sedang'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule19 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Tinggi'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule20 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sangat Tinggi'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule21 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sangat Rendah'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule22 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Rendah'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule23 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sedang'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule24 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Tinggi'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule25 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sangat Tinggi'] & irigasi['Sangat Buruk'], subsidi['Sangat Tinggi'])
rule26 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sangat Rendah'] & irigasi['Buruk'], subsidi['Sangat Tinggi'])
rule27 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Rendah'] & irigasi['Buruk'], subsidi['Sangat Tinggi'])
rule28 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sedang'] & irigasi['Buruk'], subsidi['Sangat Tinggi'])
rule29 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Tinggi'] & irigasi['Buruk'], subsidi['Sangat Tinggi'])
rule30 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sangat Tinggi'] & irigasi['Buruk'], subsidi['Sangat Tinggi'])
rule31 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sangat Rendah'] & irigasi['Buruk'], subsidi['Sangat Tinggi'])
rule32 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Rendah'] & irigasi['Buruk'], subsidi['Tinggi'])
rule33 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sedang'] & irigasi['Buruk'], subsidi['Tinggi'])
rule34 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Tinggi'] & irigasi['Buruk'], subsidi['Tinggi'])
rule35 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sangat Tinggi'] & irigasi['Buruk'], subsidi['Tinggi'])
rule36 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sangat Rendah'] & irigasi['Buruk'], subsidi['Sangat Tinggi'])
rule37 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Rendah'] & irigasi['Buruk'], subsidi['Tinggi'])
rule38 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sedang'] & irigasi['Buruk'], subsidi['Tinggi'])
rule39 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Tinggi'] & irigasi['Buruk'], subsidi['Tinggi'])
rule40 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sangat Tinggi'] & irigasi['Buruk'], subsidi['Tinggi'])
rule41 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sangat Rendah'] & irigasi['Buruk'], subsidi['Sangat Tinggi'])
rule42 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Rendah'] & irigasi['Buruk'], subsidi['Tinggi'])
rule43 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sedang'] & irigasi['Buruk'], subsidi['Tinggi'])
rule44 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Tinggi'] & irigasi['Buruk'], subsidi['Tinggi'])
rule45 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sangat Tinggi'] & irigasi['Buruk'], subsidi['Tinggi'])
rule46 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sangat Rendah'] & irigasi['Buruk'], subsidi['Sangat Tinggi'])
rule47 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Rendah'] & irigasi['Buruk'], subsidi['Tinggi'])
rule48 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sedang'] & irigasi['Buruk'], subsidi['Tinggi'])
rule49 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Tinggi'] & irigasi['Buruk'], subsidi['Tinggi'])
rule50 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sangat Tinggi'] & irigasi['Buruk'], subsidi['Tinggi'])
rule51 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sangat Rendah'] & irigasi['Sedang'], subsidi['Sangat Tinggi'])
rule52 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Rendah'] & irigasi['Sedang'], subsidi['Sangat Tinggi'])
rule53 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sedang'] & irigasi['Sedang'], subsidi['Sangat Tinggi'])
rule54 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Tinggi'] & irigasi['Sedang'], subsidi['Sangat Tinggi'])
rule55 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sangat Tinggi'] & irigasi['Sedang'], subsidi['Sangat Tinggi'])
rule56 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sangat Rendah'] & irigasi['Sedang'], subsidi['Sangat Tinggi'])
rule57 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Rendah'] & irigasi['Sedang'], subsidi['Tinggi'])
rule58 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sedang'] & irigasi['Sedang'], subsidi['Tinggi'])
rule59 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Tinggi'] & irigasi['Sedang'], subsidi['Tinggi'])
rule60 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sangat Tinggi'] & irigasi['Sedang'], subsidi['Tinggi'])
rule61 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sangat Rendah'] & irigasi['Sedang'], subsidi['Sangat Tinggi'])
rule62 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Rendah'] & irigasi['Sedang'], subsidi['Tinggi'])
rule63 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sedang'] & irigasi['Sedang'], subsidi['Sedang'])
rule64 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Tinggi'] & irigasi['Sedang'], subsidi['Sedang'])
rule65 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sangat Tinggi'] & irigasi['Sedang'], subsidi['Sedang'])
rule66 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sangat Rendah'] & irigasi['Sedang'], subsidi['Sangat Tinggi'])
rule67 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Rendah'] & irigasi['Sedang'], subsidi['Tinggi'])
rule68 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sedang'] & irigasi['Sedang'], subsidi['Sedang'])
rule69 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Tinggi'] & irigasi['Sedang'], subsidi['Sedang'])
rule70 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sangat Tinggi'] & irigasi['Sedang'], subsidi['Sedang'])
rule71 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sangat Rendah'] & irigasi['Sedang'], subsidi['Sangat Tinggi'])
rule72 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Rendah'] & irigasi['Sedang'], subsidi['Tinggi'])
rule73 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sedang'] & irigasi['Sedang'], subsidi['Sedang'])
rule74 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Tinggi'] & irigasi['Sedang'], subsidi['Sedang'])
rule75 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sangat Tinggi'] & irigasi['Sedang'], subsidi['Sedang'])
rule76 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sangat Rendah'] & irigasi['Baik'], subsidi['Sangat Tinggi'])
rule77 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Rendah'] & irigasi['Baik'], subsidi['Sangat Tinggi'])
rule78 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sedang'] & irigasi['Baik'], subsidi['Sangat Tinggi'])
rule79 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Tinggi'] & irigasi['Baik'], subsidi['Sangat Tinggi'])
rule80 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sangat Tinggi'] & irigasi['Baik'], subsidi['Sangat Tinggi'])
rule81 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sangat Rendah'] & irigasi['Baik'], subsidi['Sangat Tinggi'])
rule82 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Rendah'] & irigasi['Baik'], subsidi['Tinggi'])
rule83 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sedang'] & irigasi['Baik'], subsidi['Tinggi'])
rule84 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Tinggi'] & irigasi['Baik'], subsidi['Tinggi'])
rule85 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sangat Tinggi'] & irigasi['Baik'], subsidi['Tinggi'])
rule86 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sangat Rendah'] & irigasi['Baik'], subsidi['Sangat Tinggi'])
rule87 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Rendah'] & irigasi['Baik'], subsidi['Tinggi'])
rule88 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sedang'] & irigasi['Baik'], subsidi['Sedang'])
rule89 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Tinggi'] & irigasi['Baik'], subsidi['Sedang'])
rule90 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sangat Tinggi'] & irigasi['Baik'], subsidi['Sedang'])
rule91 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sangat Rendah'] & irigasi['Baik'], subsidi['Sangat Tinggi'])
rule92 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Rendah'] & irigasi['Baik'], subsidi['Tinggi'])
rule93 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sedang'] & irigasi['Baik'], subsidi['Sedang'])
rule94 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Tinggi'] & irigasi['Baik'], subsidi['Rendah'])
rule95 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sangat Tinggi'] & irigasi['Baik'], subsidi['Rendah'])
rule96 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sangat Rendah'] & irigasi['Baik'], subsidi['Sangat Tinggi'])
rule97 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Rendah'] & irigasi['Baik'], subsidi['Tinggi'])
rule98 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sedang'] & irigasi['Baik'], subsidi['Sedang'])
rule99 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Tinggi'] & irigasi['Baik'], subsidi['Rendah'])
rule100 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sangat Tinggi'] & irigasi['Baik'], subsidi['Rendah'])
rule101 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sangat Rendah'] & irigasi['Sangat Baik'], subsidi['Sangat Tinggi'])
rule102 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Rendah'] & irigasi['Sangat Baik'], subsidi['Sangat Tinggi'])
rule103 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sedang'] & irigasi['Sangat Baik'], subsidi['Sangat Tinggi'])
rule104 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Tinggi'] & irigasi['Sangat Baik'], subsidi['Sangat Tinggi'])
rule105 = ctrl.Rule(luas_lahan['Sangat Kecil'] & produksi_padi['Sangat Tinggi'] & irigasi['Sangat Baik'], subsidi['Sangat Tinggi'])
rule106 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sangat Rendah'] & irigasi['Sangat Baik'], subsidi['Sangat Tinggi'])
rule107 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Rendah'] & irigasi['Sangat Baik'], subsidi['Tinggi'])
rule108 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sedang'] & irigasi['Sangat Baik'], subsidi['Tinggi'])
rule109 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Tinggi'] & irigasi['Sangat Baik'], subsidi['Tinggi'])
rule110 = ctrl.Rule(luas_lahan['Kecil'] & produksi_padi['Sangat Tinggi'] & irigasi['Sangat Baik'], subsidi['Tinggi'])
rule111 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sangat Rendah'] & irigasi['Sangat Baik'], subsidi['Sangat Tinggi'])
rule112 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Rendah'] & irigasi['Sangat Baik'], subsidi['Tinggi'])
rule113 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sedang'] & irigasi['Sangat Baik'], subsidi['Sedang'])
rule114 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Tinggi'] & irigasi['Sangat Baik'], subsidi['Sedang'])
rule115 = ctrl.Rule(luas_lahan['Sedang'] & produksi_padi['Sangat Tinggi'] & irigasi['Sangat Baik'], subsidi['Sedang'])
rule116 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sangat Rendah'] & irigasi['Sangat Baik'], subsidi['Sangat Tinggi'])
rule117 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Rendah'] & irigasi['Sangat Baik'], subsidi['Tinggi'])
rule118 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sedang'] & irigasi['Sangat Baik'], subsidi['Sedang'])
rule119 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Tinggi'] & irigasi['Sangat Baik'], subsidi['Rendah'])
rule120 = ctrl.Rule(luas_lahan['Besar'] & produksi_padi['Sangat Tinggi'] & irigasi['Sangat Baik'], subsidi['Rendah'])
rule121 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sangat Rendah'] & irigasi['Sangat Baik'], subsidi['Sangat Tinggi'])
rule122 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Rendah'] & irigasi['Sangat Baik'], subsidi['Tinggi'])
rule123 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sedang'] & irigasi['Sangat Baik'], subsidi['Sedang'])
rule124 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Tinggi'] & irigasi['Sangat Baik'], subsidi['Rendah'])
rule125 = ctrl.Rule(luas_lahan['Sangat Besar'] & produksi_padi['Sangat Tinggi'] & irigasi['Sangat Baik'], subsidi['Sangat Rendah'])


subsidi_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9, rule10, 
rule11, rule12, rule13, rule14, rule15, rule16, rule17, rule18, rule19, rule20, 
rule21, rule22, rule23, rule24, rule25, rule26, rule27, rule28, rule29, rule30, 
rule31, rule32, rule33, rule34, rule35, rule36, rule37, rule38, rule39, rule40, 
rule41, rule42, rule43, rule44, rule45, rule46, rule47, rule48, rule49, rule50, 
rule51, rule52, rule53, rule54, rule55, rule56, rule57, rule58, rule59, rule60, 
rule61, rule62, rule63, rule64, rule65, rule66, rule67, rule68, rule69, rule70, 
rule71, rule72, rule73, rule74, rule75, rule76, rule77, rule78, rule79, rule80, 
rule81, rule82, rule83, rule84, rule85, rule86, rule87, rule88, rule89, rule90, 
rule91, rule92, rule93, rule94, rule95, rule96, rule97, rule98, rule99, rule100, 
rule101, rule102, rule103, rule104, rule105, rule106, rule107, rule108, rule109, rule110, 
rule111, rule112, rule113, rule114, rule115, rule116, rule117, rule118, rule119, rule120, 
rule121, rule122, rule123, rule124, rule125]
)
subsidi_simulasi = ctrl.ControlSystemSimulation(subsidi_ctrl)


luas_lahan.terms.keys()      
produksi_padi.terms.keys()   
irigasi.terms.keys()         
subsidi.terms.keys() 

subsidi_simulasi.input['luas_lahan'] = 3.2
subsidi_simulasi.input['produksi_padi'] = 5.0
subsidi_simulasi.input['irigasi'] = 7.0

subsidi_simulasi.compute()

print(f"Tingkat subsidi yang diberikan: {subsidi_simulasi.output['subsidi']:.2f} juta rupiah per hektar")
subsidi.view(sim=subsidi_simulasi)
plt.show()